logging: # logging
  file:
    name: log/laboratoryapp.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    '[org.springframework.web]': WARN
    '[org.hibernate]': INFO
    '[com.ozgur]': INFO

server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
spring:
  datasource:
    password: db_password
    url: jdbc:postgresql://localhost:5432/laboratory-reporting-application
    username: db_user
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 100
  profiles:
    active:
      - dev

# Before Spring Boot 2.4, the order in (profiles) 'active' was important,
# for 2.4 and later the order of the codes below is important. (The last one is valid.)

---
spring:
  profiles: production
laboratory:
  upload-path-for-profile-picture: uploads-production/profilepictures/
  upload-path-for-report-picture: uploads-production/reportpictures/
---
spring:
  profiles: dev
laboratory:
  upload-path-for-profile-picture: uploads-dev/profilepictures/
  upload-path-for-report-picture: uploads-dev/reportpictures/

#  %d:       Represents date and time information.
#  %-5level: Represents the log level. In this case, the log level is displayed five characters wide, aligned to the left.
#  [%thread]:Represents the thread name.
#  %logger:  Represents the logger name.
#  %msg:     Represents the log message.
#  %n:       New line character.