name: laboratory-deploy

on:
  push:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update submodules
      run: git submodule update --init --recursive
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: '20-v8-canary'
    - name: Setup Java JDK
      uses: actions/setup-java@v3.12.0
      with:
        java-version: 17
        distribution: 'adopt'
        
    - run: npm ci
      working-directory: ./laboratory-reporting-frontend

    - name: Build React App
      run: CI=false npm run build --if-present
      working-directory: ./laboratory-reporting-frontend

    - name: Create Spring Resources Directory
      run: mkdir -p src/main/resources/static
      working-directory: ./
      
    - name: Copy React Build to Spring Resources
      run: cp -a laboratory-reporting-frontend/build/. src/main/resources/static/
      working-directory: ./

    - name: Make mvnw Executable
      run: chmod +x mvnw
      working-directory: ./

    - name: Build with Maven Wrapper
      run: ./mvnw clean install
      working-directory: ./
        
    - name: Build Spring
      #run: ./mvnw -B package --file pom.xml
      run: ./mvnw --batch-mode --update-snapshots package
      working-directory: ./

    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{secrets.USERNAME}}
        server: ${{secrets.IP}}
        ssh_private_key: ${{secrets.SSH}}
        local_path: target/laboratory-reporting-application-0.0.1-SNAPSHOT.jar
        remote_path: /home/halilakgun0

   # - name: Add Delay
   #   run: sleep 10

    - name: Remote SSH Commands
      uses: fifsky/ssh-action@v0.0.6
      with:
        user: ${{secrets.USERNAME}}
        host: ${{secrets.IP}}
        key: ${{secrets.SSH}}
        command: |
         pkill -u halilakgun0 'java'
         sleep 15
         nohup java -jar -Djava.security.edg=file:/dev/./urandom laboratory-reporting-application-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &

